// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfbFkgx-1kI_4Jg8CQXqBhA_2rxF4kqds',
    appId: '1:1027985224810:web:21374ae965b56da7aa8613',
    messagingSenderId: '1027985224810',
    projectId: 'gezbot-112ee',
    authDomain: 'gezbot-112ee.firebaseapp.com',
    storageBucket: 'gezbot-112ee.appspot.com',
    measurementId: 'G-C62W3BPT95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChOsZB-uVwP5WyNF0mdFYHg7J0rQZM-vI',
    appId: '1:1027985224810:android:57e468075dd35bf9aa8613',
    messagingSenderId: '1027985224810',
    projectId: 'gezbot-112ee',
    storageBucket: 'gezbot-112ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjTip6l9r150Q4iWZPIt8GRwFiDDv8NtM',
    appId: '1:1027985224810:ios:d476dbe3425dc936aa8613',
    messagingSenderId: '1027985224810',
    projectId: 'gezbot-112ee',
    storageBucket: 'gezbot-112ee.appspot.com',
    iosClientId: '1027985224810-2lq9uqjp351fu4evn7k2r0n4m28tuqjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gezbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjTip6l9r150Q4iWZPIt8GRwFiDDv8NtM',
    appId: '1:1027985224810:ios:7e5195b31fcca204aa8613',
    messagingSenderId: '1027985224810',
    projectId: 'gezbot-112ee',
    storageBucket: 'gezbot-112ee.appspot.com',
    iosClientId: '1027985224810-b96km9olgiui5p9k90bhqq8174dundob.apps.googleusercontent.com',
    iosBundleId: 'com.example.gezbot.RunnerTests',
  );
}
